sudo: required
services:
  - docker

before_install:
    - docker build -t hatembendahmen/docker-react -f Dockerfile.dev .

script:
  - docker run hatembendahmen/docker-react npm run test -- --coverage